/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ApiRemyChatRouteImport } from './routes/api.remy-chat'
import { Route as ScheduleIndexRouteImport } from './routes/schedule.index'
import { Route as SpeakersIndexRouteImport } from './routes/speakers.index'
import { Route as SpeakersSlugRouteImport } from './routes/speakers.$slug'
import { Route as TalksIndexRouteImport } from './routes/talks.index'
import { Route as TalksSlugRouteImport } from './routes/talks.$slug'
import { Route as TranokalaBetterAuthRouteImport } from './routes/tranokala/better-auth'
import { Route as TranokalaConvexRouteImport } from './routes/tranokala/convex'
import { Route as TranokalaSinginRouteImport } from './routes/tranokala/singin'
import { Route as TranokalaSingupRouteImport } from './routes/tranokala/singup'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRemyChatRoute = ApiRemyChatRouteImport.update({
  id: '/api/remy-chat',
  path: '/api/remy-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleIndexRoute = ScheduleIndexRouteImport.update({
  id: '/schedule/',
  path: '/schedule/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeakersIndexRoute = SpeakersIndexRouteImport.update({
  id: '/speakers/',
  path: '/speakers/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeakersSlugRoute = SpeakersSlugRouteImport.update({
  id: '/speakers/$slug',
  path: '/speakers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TalksIndexRoute = TalksIndexRouteImport.update({
  id: '/talks/',
  path: '/talks/',
  getParentRoute: () => rootRouteImport,
} as any)
const TalksSlugRoute = TalksSlugRouteImport.update({
  id: '/talks/$slug',
  path: '/talks/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TranokalaBetterAuthRoute = TranokalaBetterAuthRouteImport.update({
  id: '/tranokala/better-auth',
  path: '/tranokala/better-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const TranokalaConvexRoute = TranokalaConvexRouteImport.update({
  id: '/tranokala/convex',
  path: '/tranokala/convex',
  getParentRoute: () => rootRouteImport,
} as any)
const TranokalaSinginRoute = TranokalaSinginRouteImport.update({
  id: '/tranokala/singin',
  path: '/tranokala/singin',
  getParentRoute: () => rootRouteImport,
} as any)
const TranokalaSingupRoute = TranokalaSingupRouteImport.update({
  id: '/tranokala/singup',
  path: '/tranokala/singup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api/remy-chat': typeof ApiRemyChatRoute
  '/speakers/$slug': typeof SpeakersSlugRoute
  '/talks/$slug': typeof TalksSlugRoute
  '/tranokala/better-auth': typeof TranokalaBetterAuthRoute
  '/tranokala/convex': typeof TranokalaConvexRoute
  '/tranokala/singin': typeof TranokalaSinginRoute
  '/tranokala/singup': typeof TranokalaSingupRoute
  '/schedule/': typeof ScheduleIndexRoute
  '/speakers/': typeof SpeakersIndexRoute
  '/talks/': typeof TalksIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api/remy-chat': typeof ApiRemyChatRoute
  '/speakers/$slug': typeof SpeakersSlugRoute
  '/talks/$slug': typeof TalksSlugRoute
  '/tranokala/better-auth': typeof TranokalaBetterAuthRoute
  '/tranokala/convex': typeof TranokalaConvexRoute
  '/tranokala/singin': typeof TranokalaSinginRoute
  '/tranokala/singup': typeof TranokalaSingupRoute
  '/schedule': typeof ScheduleIndexRoute
  '/speakers': typeof SpeakersIndexRoute
  '/talks': typeof TalksIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api/remy-chat': typeof ApiRemyChatRoute
  '/speakers/$slug': typeof SpeakersSlugRoute
  '/talks/$slug': typeof TalksSlugRoute
  '/tranokala/better-auth': typeof TranokalaBetterAuthRoute
  '/tranokala/convex': typeof TranokalaConvexRoute
  '/tranokala/singin': typeof TranokalaSinginRoute
  '/tranokala/singup': typeof TranokalaSingupRoute
  '/schedule/': typeof ScheduleIndexRoute
  '/speakers/': typeof SpeakersIndexRoute
  '/talks/': typeof TalksIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/api/remy-chat'
    | '/speakers/$slug'
    | '/talks/$slug'
    | '/tranokala/better-auth'
    | '/tranokala/convex'
    | '/tranokala/singin'
    | '/tranokala/singup'
    | '/schedule/'
    | '/speakers/'
    | '/talks/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/api/remy-chat'
    | '/speakers/$slug'
    | '/talks/$slug'
    | '/tranokala/better-auth'
    | '/tranokala/convex'
    | '/tranokala/singin'
    | '/tranokala/singup'
    | '/schedule'
    | '/speakers'
    | '/talks'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/api/remy-chat'
    | '/speakers/$slug'
    | '/talks/$slug'
    | '/tranokala/better-auth'
    | '/tranokala/convex'
    | '/tranokala/singin'
    | '/tranokala/singup'
    | '/schedule/'
    | '/speakers/'
    | '/talks/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApiRemyChatRoute: typeof ApiRemyChatRoute
  SpeakersSlugRoute: typeof SpeakersSlugRoute
  TalksSlugRoute: typeof TalksSlugRoute
  TranokalaBetterAuthRoute: typeof TranokalaBetterAuthRoute
  TranokalaConvexRoute: typeof TranokalaConvexRoute
  TranokalaSinginRoute: typeof TranokalaSinginRoute
  TranokalaSingupRoute: typeof TranokalaSingupRoute
  ScheduleIndexRoute: typeof ScheduleIndexRoute
  SpeakersIndexRoute: typeof SpeakersIndexRoute
  TalksIndexRoute: typeof TalksIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/remy-chat': {
      id: '/api/remy-chat'
      path: '/api/remy-chat'
      fullPath: '/api/remy-chat'
      preLoaderRoute: typeof ApiRemyChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule/': {
      id: '/schedule/'
      path: '/schedule'
      fullPath: '/schedule/'
      preLoaderRoute: typeof ScheduleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speakers/': {
      id: '/speakers/'
      path: '/speakers'
      fullPath: '/speakers/'
      preLoaderRoute: typeof SpeakersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speakers/$slug': {
      id: '/speakers/$slug'
      path: '/speakers/$slug'
      fullPath: '/speakers/$slug'
      preLoaderRoute: typeof SpeakersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talks/': {
      id: '/talks/'
      path: '/talks'
      fullPath: '/talks/'
      preLoaderRoute: typeof TalksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talks/$slug': {
      id: '/talks/$slug'
      path: '/talks/$slug'
      fullPath: '/talks/$slug'
      preLoaderRoute: typeof TalksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tranokala/better-auth': {
      id: '/tranokala/better-auth'
      path: '/tranokala/better-auth'
      fullPath: '/tranokala/better-auth'
      preLoaderRoute: typeof TranokalaBetterAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tranokala/convex': {
      id: '/tranokala/convex'
      path: '/tranokala/convex'
      fullPath: '/tranokala/convex'
      preLoaderRoute: typeof TranokalaConvexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tranokala/singin': {
      id: '/tranokala/singin'
      path: '/tranokala/singin'
      fullPath: '/tranokala/singin'
      preLoaderRoute: typeof TranokalaSinginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tranokala/singup': {
      id: '/tranokala/singup'
      path: '/tranokala/singup'
      fullPath: '/tranokala/singup'
      preLoaderRoute: typeof TranokalaSingupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApiRemyChatRoute: ApiRemyChatRoute,
  SpeakersSlugRoute: SpeakersSlugRoute,
  TalksSlugRoute: TalksSlugRoute,
  TranokalaBetterAuthRoute: TranokalaBetterAuthRoute,
  TranokalaConvexRoute: TranokalaConvexRoute,
  TranokalaSinginRoute: TranokalaSinginRoute,
  TranokalaSingupRoute: TranokalaSingupRoute,
  ScheduleIndexRoute: ScheduleIndexRoute,
  SpeakersIndexRoute: SpeakersIndexRoute,
  TalksIndexRoute: TalksIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
